networks:
  pwn-server-network:
    name: pwn-server-network
    driver: bridge

services:
  pwn-master-server:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: pwn-master-server
    image: pwn-master-server:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - pwn-server-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=master
      - POSTGRES_PASSWORD=5mboQV6MI978
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - pwn-server-network